# =================================================================
# 日志捕获监听配置
# =================================================================
listen:
  # 监听标准 Syslog 端口 514
  - port: 514
    protocols: [udp, tcp]
  # 也可以配置监听其他端口
  # - port: 1514
  #   protocols: [udp]

# =================================================================
# 日志过滤配置 (现为白名单模式)
# =================================================================
filtered_sources: # 配置要**处理并转发**的源 IP 或子网列表 (白名单)。留空则处理所有非本机流量。
  # - 192.168.1.0/24   # 示例：只处理来自此 C 段的日志
  # - 10.10.10.5       # 示例：只处理来自单个 IP 的日志

# =================================================================
# 远端日志服务器配置 (替换了原有的本地存储配置)
# =================================================================
remote_servers:
  # 第一台服务器：使用 TCP 协议，地址和端口
  - protocol: tcp
    address: "192.168.4.7:9514"
  
  # 第二台服务器：使用 UDP 协议，地址和端口
  - protocol: udp
    address: "192.168.5.8:514"
  
  # 可以继续添加其他服务器...
  # - protocol: tcp
  #   address: "192.168.1.102:5140"

# =================================================================
# 日志发送队列和连接控制配置 (用于保证 TCP 健壮性和避免阻塞)
# =================================================================
log_queue_size: 10000        # 日志缓冲队列大小。当发送速度慢于捕获速度时，日志会在此队列中排队，队列满时新日志会被丢弃。

dial_timeout: 5s             # TCP 连接建立的超时时间。如果 5 秒内无法连接，则失败并等待重连。
write_timeout: 3s            # TCP 写入数据的超时时间。防止因远端服务器阻塞导致写入操作永久挂起。
reconnect_delay: 5s          # TCP 连接断开或失败后，等待多久尝试重连。


# 网卡配置
# =================================================================
interfaces: # 指定要监听的网卡名称列表。留空则监听 pcap 找到的所有网卡。
  - ens18    
  # - en0     # macOS 上的示例网卡名称
  # - \Device\NPF_{...} # Windows 上的示例网卡名称 (请使用 pcap.FindAllDevs 查找实际名称)